(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"ugg_weatherAPI_women_300x600_atlas_NP_", frames: [[0,0,300,600],[0,602,300,600],[0,1204,300,600],[302,0,300,600],[302,602,300,600],[302,1204,300,600]]}
];


// symbols:



(lib.cold_plate_300x600 = function() {
	this.initialize(ss["ugg_weatherAPI_women_300x600_atlas_NP_"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.rain_plate_300x600 = function() {
	this.initialize(ss["ugg_weatherAPI_women_300x600_atlas_NP_"]);
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.snow_plate_300x600 = function() {
	this.initialize(ss["ugg_weatherAPI_women_300x600_atlas_NP_"]);
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.women_COLD_bg_300x600 = function() {
	this.initialize(ss["ugg_weatherAPI_women_300x600_atlas_NP_"]);
	this.gotoAndStop(3);
}).prototype = p = new cjs.Sprite();



(lib.women_RAIN_bg_300x600 = function() {
	this.initialize(ss["ugg_weatherAPI_women_300x600_atlas_NP_"]);
	this.gotoAndStop(4);
}).prototype = p = new cjs.Sprite();



(lib.women_SNOW_bg_300x600 = function() {
	this.initialize(ss["ugg_weatherAPI_women_300x600_atlas_NP_"]);
	this.gotoAndStop(5);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.m_weathericons = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// FlashAICB
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(255,255,255,0.008)").s().dr(-15,-15,30,30);
	this.shape.setTransform(15,15);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.m_weathericons, new cjs.Rectangle(0,0,30,30), null);


(lib.m_highlight = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(255,255,255,0.749)").s().dr(-25,-37.5,50,75);
	this.shape.setTransform(25,37.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.m_highlight, new cjs.Rectangle(0,0,50,75), null);


(lib.m_logo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AudQkQnal9AAqnQAAp4Gll2QGPljKWAAQDJAADEApQDBArDlBhQCIA7A0AAQAnAAAxgtIAxAdIkbJxIg4gWQAAgagLgfQgFgPgMgaQgPgdgygnQhzhcjQg6QjVg+i8AAQl/AAkADnQkeEHAAGrQAAGgEXEBQD9DrGkAAQDHAADJgyQDDg0CUhXIAAlkIpeAAQg5AAgbAbQgeAfgQBBIg6AAIAApnIA6AAQAQBHAeAcQAdAZA3AAISNAAIAAA8Qg+ASgcAgQgbAfAAA8IAAIeQAAA8AZAfQAdAgA/ASIAAAuQq6GsqRAAQpRAAl5kug");
	this.shape.setTransform(297.65,136.225);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AlzPxQg4gMgsgQIghgMIAAlxIACgNIAlAXQAwAbA5AWQC2BFDJgLQFUgRCyhbQBagtAVgqIAAkMInaAAQgpAAgYAUQgYAVgMAzIgtAAIAAnNIAtAAQAPA4AVARQAYAUApAAIOKAAIAAAsQg0AQgRAWQgVAZAEAqIAAGVQAAAuATAWQASAWA1APIAAAlQjnDDkjBgQkABVkVAAQjiAAiygpgAw4B9QgHhxABgnQAHiIARhfQARhfAXgUQAIAEACBAICCAqIE5qjIApgUQA1gXBCgTQDUg7EAAMQBqAFA2AFQBUAHBBAPQCSAgC3BJQBeAmAqAAQAaAAArghIAmAVIjfHYIgogVQgCgvgLgUQgKgTgogfQhWhCilgvQioguiPAAQkpAAjHCuQjkDJgFE6QAAA3AKBag");
	this.shape_1.setTransform(483.3441,118.6665);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("Ap4M2QiAhWgyiSQgwiRgBjJIAAwrQAAgpgRgYQgRgWgvgOIAAgtIIfAAIAAAtQgvAOgRAWQgTAYAAAqIAAO3QABCnAQBMQAOBNAwA3QB6CPEmAAQEpAAB7iPQAqg1ARhPQARhVgBieIAAu1QAAgrgRgYQgQgWgwgOIAAgtIH/AAIAAAtQguAOgRAWQgSAXABAqIAACWQiWCuhIDgQhGDaAAERQAACvAVCGQAXCZA0B7QjPConHAAQmeAAjciUg");
	this.shape_2.setTransform(94.05,114.55);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AhHBHQgegdAAgqQAAgqAegdQAegdAqABQAqAAAdAcQAeAcAAArQAAArgeAdQgdAdgqgBQgqAAgegdgAg6g8QgYAZAAAjQABAjAXAYQAYAYAiAAQAhAAAYgYQAYgYAAgjQAAgjgYgZQgYgXghAAQgiAAgYAXgAAdA5IgegyIgUAAIAAAyIgTAAIAAhyIArAAQAVAAAKAIQAJAIAAARQAAAcgeADIAiAygAgWgHIAWAAQANAAAGgDQAIgEAAgMQAAgSgZAAIgYAAg");
	this.shape_3.setTransform(588.125,71.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.m_logo, new cjs.Rectangle(0,0,598.3,272.5), null);


(lib.m_images = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(3));

	// images
	this.instance = new lib.women_RAIN_bg_300x600();
	this.instance.parent = this;

	this.instance_1 = new lib.women_SNOW_bg_300x600();
	this.instance_1.parent = this;

	this.instance_2 = new lib.women_COLD_bg_300x600();
	this.instance_2.parent = this;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_2}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.m_hider = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().dr(-150,-300,300,600);
	this.shape.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.m_hider, new cjs.Rectangle(0,0,300,600), null);


(lib.m_arrowbutton = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// hit
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(255,0,255,0.008)").s().dr(-90,-20,180,40);
	this.shape.setTransform(90,20);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// arrow
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AiNg4IAdgcIBwBwIBxhwIAcAcIiNCNg");
	this.shape_1.setTransform(90,12.025);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.m_arrowbutton, new cjs.Rectangle(0,0,180,40), null);


(lib.headline_mc = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(3));

	// headline copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgLANQgGgFAAgIQAAgGAGgGQAFgFAGAAQAIAAAFAGQAFAFAAAHQAAAIgFAEQgFAFgIAAQgGAAgFgFg");
	this.shape.setTransform(196.425,69.075);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgyBuIAAgEIAPgDQAHgCAHgHIADgGIABgHIAAgKIAAgKIAAgLIABgPIAAgSIAAgQIAAhiIgLAAIgJAAIgIAAIgKAAQgMAAgHADQgHACgHAGIgFAGIgGAJIgIALIgEALIgDgBIAJg5IANADIARABIAUAAIASAAIARAAIATAAIATAAIASAAIARAAIAUAAIARgCIAOgEIAJA7IgDABIgFgLIgHgMIgHgJIgFgGQgHgHgHgBQgIgCgLAAIgKAAIgIAAIgJAAIgLAAIAAAUIAAAbIAAAcIAAAWIAABCIAAARQAAAHADAEQAFAHAHACIAPADIAAAEg");
	this.shape_1.setTransform(181.75,59.85);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgrBmQgUgIgQgOQgPgPgIgUQgJgUAAgZQAAgYAJgVQAJgUAQgPQAQgOAVgIQAVgHAXAAQAZAAAUAJQAVAJANAPQAPAPAHAUQAIAUAAAVQgBAXgIAVQgJAUgQAPQgPAPgVAIQgUAIgXAAQgWAAgVgIgAghhfQgOAKgJAPQgKAPgEATQgEATAAASQAAAVAEATQAGATAJAOQAKAOAOAJQAOAJARAAQAUAAAOgKQANgKAKgPQAJgPAFgTQAFgSAAgTQAAgSgFgSQgFgTgKgPQgIgPgPgKQgOgJgTAAQgTAAgOAJg");
	this.shape_2.setTransform(158.55,59.925);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgrBmQgUgIgQgOQgPgPgIgUQgKgUABgZQAAgYAJgVQAJgUAQgPQAQgOAVgIQAVgHAXAAQAZAAAUAJQAVAJAOAPQAOAPAHAUQAIAUAAAVQgBAXgIAVQgJAUgQAPQgPAPgVAIQgVAIgWAAQgWAAgVgIgAghhfQgOAKgJAPQgKAPgEATQgEATAAASQAAAVAEATQAGATAJAOQAJAOAPAJQAOAJARAAQAUAAANgKQAOgKAKgPQAJgPAFgTQAFgSAAgTQAAgSgFgSQgFgTgJgPQgJgPgPgKQgOgJgTAAQgTAAgOAJg");
	this.shape_3.setTransform(134.35,59.925);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhgBsIAAgDIAPgEQAGgCAFgFIACgGIACgIIABgJIAAgJIAAgMIABgQIAAgSIAAgQIAAgQIAAgNIAAgOIgBgPIAAgMIgBgKIgCgJIgDgGQgEgEgFgCIgMgDIAAgDIBkAAIAWABQAKABAKAEQAPAGAKAMQAKAMAAARQAAAUgNANQgNAMgUADIAAACQALABAKADQALAEAIAHQAIAHAFAJQAFAKAAAMQAAAKgDAKQgEAIgFAGQgFAIgHAEQgHAFgGACQgMAEgOABIgbABgAggATIAAASIAAAQIABAMIABASQAAAIAEAFQADADAFACQAGADAKAAIASgBQAKgCAJgFQANgGAHgLQAHgLAAgQQAAgJgDgHQgDgIgFgGQgFgGgGgGQgHgEgIgCIgNgEIgPAAIgdAAgAgVhmIgIABIgBADIAAAEIgBAFIAAAJIgBAYIAAAXIAAAUIAAAJIARAAIALAAQAagBAOgOQAOgOAAgVQAAgOgIgNQgHgLgMgFQgNgGgUAAg");
	this.shape_4.setTransform(110.725,60);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AhiBsIAAgDIANgEQAHgDAEgEIADgGIABgIIABgJIABgKIAAgLIAAgQIAAgSIAAgQIAAg6IAAgLIgBgMIgBgJIgDgFQgEgFgFgCIgOgCIAAgDIClAAIAUAyIgDABQgYgfgVgKQgFgCgOgCQgOgCgTAAIgNABIgKAAIgBAUIAAAjIAAATIAAANIAAAIIAAADIAGAAIALAAIALgBIAJgBQAJgCAGgEQAGgEAEgFIAGgLIAEgQIADAAIAABeIgDAAQgDgKgFgKQgFgKgFgFQgFgEgHgDQgGgDgIgBIgIAAIgGAAIgGAAIgIAAIAAANIAAAQIAAAJIAAAKIAAAKIAAAHIABASQABAJADADQACAFALACQAKACALAAIANgBIAQgBQAKgBAIgEQAIgEAIgGQAHgGAHgJIAPgWIADAAIgPA6g");
	this.shape_5.setTransform(197.675,32.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgrBmQgUgIgQgOQgPgPgIgUQgKgUABgZQAAgYAJgVQAJgUAQgPQAQgOAVgIQAVgHAXAAQAZAAAUAJQAVAJAOAPQAOAPAHAUQAIAUAAAVQgBAXgIAVQgJAUgQAPQgPAPgVAIQgVAIgWAAQgWAAgVgIgAghhfQgOAKgJAPQgKAPgEATQgEATAAASQAAAVAEATQAGATAJAOQAJAOAPAJQAOAJARAAQAUAAANgKQAOgKAKgPQAJgPAFgTQAFgSAAgTQAAgSgFgSQgFgTgJgPQgJgPgPgKQgOgJgTAAQgTAAgOAJg");
	this.shape_6.setTransform(174.4,32.225);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAdBsIAAgDQALgBAHgDQAIgDACgEIABgEIABgGIAAgHIABgIIAAgUIAAgUIAAgRIAAgLIh2AAIAABBIABARQAAAHADAEQADAFAHADQAHADAFAAIAAADIhYAAIAAgDIAPgEQAGgDAEgEIACgFIABgIIABgKIABgKIAAgLIAAgQIAAgSIAAgQIAAg6IAAgLIAAgKIgCgIIgDgGQgEgFgGgDIgOgDIAAgDIBZAAIAAADIgJACIgIADQgEADgDAEQgCAFgBAHIgBAXIAAAXIAAATIAAALIB2AAIAAgRIAAgQIAAgPIAAgSIgBgMQAAgGgDgEQgFgHgHgDIgOgCIAAgDIBaAAIAAADQgGABgIADQgGADgEAGIgCAGIgBAJIAAAJIAAAJIAAA0IAAATIAAARIAAASIAAATIABAQQABAIABADQAEAGAHACIAOADIAAADg");
	this.shape_7.setTransform(148.7,32.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAbBuIAAgDIAFgBIAHgBIAHgFQACgCAAgFIgBgIIgFgPIgHgUIgIgXIhPAAIgJAWIgIAVQgGAQAAAGQAAAEACADIAGAFIAIACIAJABIAAADIhAAAIAAgEQAHAAAGgDIAHgFIAGgKIAMgXIAOggIAQgkIARgnIAPgkIgDgGIAKgGIAHgHIAFgGIADgGIADAAIARAvIAQArIAPAnIAPAnIAGAPIAGAOIADAEIAFAGIAJAGQAFACAHAAIAAAEgAAYAVIgKgaIgKgaIgIgXIgHgRIgFANIgJAUIgLAbIgNAgIBJAAg");
	this.shape_8.setTransform(124.775,32.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgyBuIAAgDIAPgEQAHgBAHgJIADgEIAAgIIABgJIAAgKIAAgMIABgPIAAgRIAAgRIAAhiIgLAAIgJAAIgIAAIgKAAQgLAAgIACQgHADgHAGIgFAGIgHAJIgHALIgEALIgDgBIAJg5IANADIARAAIAUABIARAAIASAAIATAAIATAAIASAAIARAAIAUgBIARgBIAOgDIAJA6IgCABIgGgLIgHgLIgHgKIgFgGQgHgHgIgBQgGgCgMAAIgKAAIgJAAIgIAAIgLAAIAAATIAAAcIAAAbIAAAXIAABCIAAARQABAHACAEQAEAGAJADIAOAEIAAADg");
	this.shape_9.setTransform(103.2,32.15);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AhiBsIAAgDIANgEQAHgDAEgFIADgFIABgHIABgKIABgKIAAgLIAAgQIAAgSIAAgQIAAg7IAAgKIgBgLIgBgJIgDgGQgEgFgFgCIgOgCIAAgDIClAAIAUAxIgDACQgYgegVgLQgFgCgOgCQgOgCgTAAIgNAAIgKABIgBAUIAAAjIAAATIAAANIAAAIIAAADIAGAAIALAAIALgBIAJgBQAJgDAGgDQAGgEAEgFIAGgLIAEgQIADAAIAABeIgDAAQgDgKgFgKQgFgKgFgFQgFgFgHgCQgGgDgIAAIgIgBIgGAAIgGAAIgIAAIAAAMIAAARIAAAJIAAAKIAAAJIAAAIIABASQABAJADADQACAFALACQAKABALAAIANAAIAQgBQAKgCAIgDQAIgDAIgHQAHgGAHgJIAPgWIADAAIgPA6g");
	this.shape_10.setTransform(197.275,4.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAdBsIAAgDQALgBAHgDQAIgDADgEIABgDIAAgHIABgIIAAgHIAAgVIAAgTIAAgRIAAgLIh1AAIAABBIAAARQAAAHACAEQAEAFAHADQAGADAHAAIAAADIhZAAIAAgDIAOgEQAIgDADgEIACgFIACgIIAAgKIAAgKIAAgLIABgQIAAgSIAAgQIAAg7IAAgKIgBgKIgBgIIgCgHQgFgEgGgDIgOgDIAAgDIBaAAIAAADIgJACIgJAEQgEACgDAEQgDAFAAAHIAAAWIAAAYIAAATIAAALIB1AAIAAgRIAAgQIAAgPIAAgSIgBgMQgBgFgCgFQgFgHgHgDIgOgCIAAgDIBbAAIAAADQgIABgHADQgGADgEAGIgBAGIgBAIIgBAKIAAAJIAAA0IAAASIAAASIAAASIABATIAAAQQAAAIACACQAEAGAGADIAPADIAAADg");
	this.shape_11.setTransform(172.5,4.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgyBtIAAgCIAPgEQAHgBAHgJIADgEIABgIIAAgJIAAgKIAAgLIABgQIAAgRIAAgSIAAhiIgLAAIgJAAIgIAAIgKAAQgLABgIACQgHADgHAGIgFAGIgHAJIgHALIgEALIgDgBIAJg5IANACIARABIAUABIASAAIARAAIATAAIATAAIASAAIARAAIAUgBIARgBIAOgDIAJA6IgDABIgFgMIgHgKIgHgKIgFgHQgHgFgIgCQgHgCgLgBIgKAAIgJAAIgIAAIgLAAIAAAUIAAAbIAAAcIAAAXIAABCIAAAQQAAAJADADQAEAGAJADIAOAEIAAACg");
	this.shape_12.setTransform(148.1,4.45);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("ABQBqIgvg2IgmgvIgmgrIgngsIAAB+IABAbQABAMADAGQADAHAIADQAGAEANACIAAACIhKAAIAAgCIAOgEQAHgDAFgHQAEgGABgNIACgcIABgfIAAglIAAgOIAAgLIAAgMIAAgOQgBgJgEgGQgCgFgFgDQgFgEgFAAIgKgDIAAgDIA9AAICNCmIAAhmIgBgWQAAgLgCgGQgDgJgHgFQgIgFgOgDIAAgDIBKAAIAAADQgMACgGAEQgHAEgDAJQgCAEgBANIgCAZIgBAfIAAAlIAAATIAAAVIAAAXIAAATIgBABIgBABQgDAAgDgCg");
	this.shape_13.setTransform(117.7,4.65);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgsBsIAAgDIANgEQAHgDAEgFIADgFIABgHIABgKIAAgKIAAgLIAAgQIAAgSIAAgQIAAg7IAAgKIAAgKIgCgIIgCgHQgEgEgHgDIgOgDIAAgDIBZAAIAAADIgNADQgIACgDAIQgDAFAAAIIgBAOIAAAPIAAAPIAAAQIAAARIAABDIAAARQABAHACAEQAEAFAHADIAOADIAAADg");
	this.shape_14.setTransform(98.475,4.6);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAbBuIAAgDIAFgBIAHgCIAHgEQACgCAAgFIgBgJIgFgPIgHgUIgIgWIhPAAIgJAWIgIAVQgGAQAAAHQAAADACADIAGAEIAIACIAJACIAAADIhAAAIAAgEQAHAAAGgEIAHgEIAGgKIAMgXIAOggIAQgkIARgmIAPgkIgDgIIAKgFIAHgHIAFgHIADgFIADAAIARAvIAQArIAPAnIAPAmIAGAQIAGANIADAFIAFAGIAJAFQAFADAHAAIAAAEgAAYAVIgKgaIgKgaIgIgXIgHgRIgFAMIgJAVIgLAbIgNAgIBJAAg");
	this.shape_15.setTransform(183.275,-23.3);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AhlBsIAAgDIAPgEQAHgDAEgFIADgEIACgIIABgKIAAgJIAAgMIABgQIAAgRIAAgRIAAg6IAAgLIgBgKIgBgIIgDgGQgEgEgHgDQgHgDgIgBIAAgDIBgAAIAAADIgKACIgKAEQgFACgDAGQgDAFgBAHIAAATIgBARIAAASIAAAUIAAASIAAAPIAAARIABASIAAASQABAJADAEIAEAEIAJACIALABIALABIAIAAIALgBIANgBIAMgCQAMgEAIgEQAIgGAGgHQAFgHAEgIIAIgRIADAAIgMA+g");
	this.shape_16.setTransform(162.725,-23.1);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgqBmQgVgIgPgOQgQgPgIgUQgKgUABgZQAAgYAJgVQAJgUAQgPQAQgOAVgIQAVgHAXAAQAZAAAUAJQAVAJAOAPQAOAPAHAUQAHAUABAVQAAAXgJAVQgJAUgQAPQgPAPgVAIQgVAIgWAAQgWAAgUgIgAghhfQgOAKgKAPQgJAPgEATQgEATAAASQAAAVAFATQAEATAKAOQAJAOAPAJQAOAJARAAQAUAAANgKQAPgKAJgPQAJgPAFgTQAEgSABgTQgBgSgEgSQgFgTgJgPQgJgPgPgKQgOgJgTAAQgTAAgOAJg");
	this.shape_17.setTransform(139.4,-23.175);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AhlBsIAAgDIAPgEQAHgDAEgFIADgEIACgIIABgKIAAgJIAAgMIABgQIAAgRIAAgRIAAg6IAAgLIgBgKIgBgIIgDgGQgEgEgHgDQgHgDgIgBIAAgDIBgAAIAAADIgKACIgKAEQgFACgDAGQgDAFgBAHIAAATIgBARIAAASIAAAUIAAASIAAAPIAAARIABASIAAASQABAJADAEIAEAEIAJACIALABIALABIAIAAIALgBIANgBIAMgCQAMgEAIgEQAIgGAGgHQAFgHAEgIIAIgRIADAAIgMA+g");
	this.shape_18.setTransform(117.325,-23.1);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgsBsIAAgDIANgEQAHgDAEgEIADgGIABgIIABgJIAAgKIAAgLIAAgQIAAgSIAAgQIAAg6IAAgLIAAgKIgCgIIgCgGQgEgFgHgDIgOgDIAAgDIBZAAIAAADIgNADQgIACgDAIQgDAFAAAIIgBAOIAAAQIAAAOIAAAQIAAARIAABDIAAARQABAHACAEQAEAFAHADIAOADIAAADg");
	this.shape_19.setTransform(240.175,32.3);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("ABQBqIgug2IgngwIgmgqIgngsIAAB+IABAbQABAMADAGQADAHAIADQAGAEANACIAAADIhKAAIAAgDIAOgEQAHgDAFgHQAEgGABgNIACgcIABgfIAAglIAAgOIAAgMIAAgLIAAgOQgBgJgEgFQgCgGgFgDQgFgDgFgCIgKgCIAAgCIA9AAICNCkIAAhlIgBgXQAAgKgCgGQgDgJgIgFQgHgGgOgCIAAgCIBKAAIAAACQgMACgGAEQgHAFgDAIQgCAEgBANIgCAZIgBAfIAAAlIAAATIAAAVIAAAXIAAATIgBACIgBABQgDgBgDgCg");
	this.shape_20.setTransform(221.2,32.35);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgsBsIAAgDIANgEQAHgDAEgEIADgGIABgIIABgJIAAgKIAAgLIAAgQIAAgSIAAgQIAAg6IAAgLIAAgKIgCgIIgCgGQgEgFgHgDIgOgDIAAgDIBZAAIAAADIgNADQgIACgDAIQgDAFAAAIIgBAOIAAAQIAAAOIAAAQIAAARIAABDIAAARQABAHACAEQAEAFAHADIAOADIAAADg");
	this.shape_21.setTransform(201.975,32.3);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AAmBsIAAgDQAMgBAJgFQAIgFAEgGIADgKIABgLIAAgmIAAglIAAhVIgSAqIgRAkIgQAjIgSAoIgEAKIgFANIgEAMIgEAIIgCAAIgTgsIgSgrIgRglIgNgfIgLgXIgFgMIgBAiIAAAfIAAAeIAAAmIABAYQABALADAHQAEAHAHAEQAIAEANACIAAADIhPAAIAAgDQAKgCAHgEQAGgEAEgIQAFgHACgKIABgaIABgeIAAglIAAgPIAAgLIAAgMIAAgPQAAgIgDgGQgDgFgFgDIgJgEIgJgCIAAgDIA/AAIBHCjIAag5IAWgyIARgnIAIgRIA/AAIAAADQgMAAgGAFQgHAFgCAHQgCAFAAAKIgBAWIgBAcIAAAaIAAAgIABAiIABALIACAJIACAEIAGAEIAJAFQAFACAHAAIAAADg");
	this.shape_22.setTransform(181.1,32.3);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgsBnQgWgHgQgOQgPgOgIgVQgIgVAAgZIABgQQABgKAEgLQAEgLAHgLQAHgLAJgKQAPgOAVgIQAVgJAdAAQASAAAOADQANADAKAEIAPAHIAFADIAEgEIAGgIIADAAIAABBIgEAAQgDgNgHgMQgHgMgGgIQgLgKgPgGQgPgHgSAAQgSAAgRAJQgQAJgLAPQgKAPgHATQgFATAAAVQgBAXAGATQAFAUALANQAMAOAPAIQAQAIASAAQAPAAAMgFQANgFAHgLQADgEABgKIABgVIgBgTQgBgIgGgFQgGgIgSgCIAAgDIBYAAIAAADIgLADQgGACgCAEQgCADgBAHIAAAOIAAAsIgLAGIgUAIQgMAFgOADQgOADgPAAQgbAAgXgIg");
	this.shape_23.setTransform(126.35,32.175);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("Ah0BsIAAgDQAIgBAGgDQAIgDADgEIACgFIACgIIAAgKIABgJIAAgMIAAgQIAAgRIAAgRIAAg6IAAgLIAAgKIgBgIIgDgGQgFgGgGgCIgOgDIAAgDIAlAAIA4AAIAUAAIATABIAUADQAKACAJAEQAMAGAMAIQAKAIAJAMQAIALAFAQQAFAPAAATQAAAWgFARQgGARgJAMQgKANgMAIQgMAIgOAFQgNAEgPACQgPACgNAAgAgmhmIgHABIgGABIgBApIgBA8IAAAjIABAaIAAAJIABAKIACAIIADAFQAGAGAJACIARACIAPgBIAOgDQAhgJAQgbQARgbAAgmQAAgRgGgRQgFgRgKgNQgKgNgNgJQgOgKgPgCIgMgDIgSAAIgIAAg");
	this.shape_24.setTransform(101.45,32.275);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgsBsIAAgDIANgEQAHgDAEgEIADgGIABgIIABgJIAAgKIAAgLIAAgQIAAgSIAAgQIAAg6IAAgLIAAgKIgCgIIgCgGQgEgFgHgDIgOgDIAAgDIBZAAIAAADIgNADQgIACgDAIQgDAFAAAIIgBAOIAAAQIAAAOIAAAQIAAARIAABDIAAARQABAHACAEQAEAFAHADIAOADIAAADg");
	this.shape_25.setTransform(82.475,32.3);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AA0BsIgEgEIgDgDIgDgFIgHgLIgLgPIgIgNIgKgNIgMgQIgNgMQgHgGgHgCIgJgBIgHAAIAAAhIAAAZIABAQQAAAHADAFQACAEAHAEQAHAEANAAIAAADIhgAAIAAgDIAOgDQAHgDAEgFIACgFIACgIIAAgKIABgJIAAgMIAAgQIAAgRIAAgRIAAg6IAAgLIgBgLIgBgJIgDgGQgEgEgGgCIgOgDIAAgDIANAAIAXAAIAaAAIAUAAIAjABQAQABANAHQANAHAIAMQAIAMAAASQAAALgEAJQgEAJgHAGQgGAHgKAFIgSAHIAAABQAFADAFAFIAJALIARAZIAQAXQALAQALAHQAKAHAOACIAAADgAgphmIgGAAIAAAEIgBADIAAAGIgBAKIAAAYIAAAaIAAAVIAAALIAXgBQALgBAJgDQAJgDAHgFQAHgFAEgGQAEgHADgHQACgIAAgIQAAgPgIgMQgHgLgPgHIgOgFIgRgCg");
	this.shape_26.setTransform(66.275,32.275);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AAvBsIgDgCIgDgDIglgqIgjgoIgKgLIgFgCIgDABIgCAEIAAAdIAAAYIACAQQAAAHADAFIAGAEIAIAEIAIACIAHABIAAADIhgAAIAAgDIAOgDQAHgDAEgEIACgGIACgIIAAgKIAAgKIABgLIAAgQIAAgSIAAgQIAAg6IgBgWQgBgJgDgEQgEgFgGgDIgOgDIAAgDIBdAAIAAADIgLACQgGABgEADQgEADgDAIQgDAGAAANIgBANIAAAOIAAATIAAAaIAPgKIATgSIATgVIARgSIAJgMQAEgGAAgFQAAgJgGgEQgGgEgIgBIAAgDIBRAAIAAADQgPABgQAMQgQAMgQAOIgNAMIgNAOIgLAMIgMAMIAMANIATAXIAaAdIAaAdIAHAHIAIAHIAGAEIAEADIAKADIAPACIAAADg");
	this.shape_27.setTransform(231.025,32.3);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AghBnQgXgIgPgPQgQgOgIgUQgJgUAAgZIABgLIADgPIAFgQIAJgRQAGgLAJgJQAKgJAMgHQANgHAQgFQAQgEASAAQATAAANAEQAOADAJAEIANAHIAGADIACgBIAEgDIAEgFIADgFIAEAAIAABDIgEAAQgEgOgIgNQgHgMgLgKQgLgJgNgFQgNgGgPAAQgUAAgQAKQgQAJgLAPQgLAPgGAUQgGATAAAUQAAAVAGATQAGATAMAOQALAOAQAIQAQAIATAAQAQAAAOgFQANgGALgKQAKgJAIgMQAHgMADgNIAEAAIgBBCIgEAAIgHgJQgEgFgCAAIgFAEIgOAHQgJADgNADQgNADgRAAQgbAAgWgIg");
	this.shape_28.setTransform(206.375,32.125);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("Ah0BsIAAgDQAHgBAIgDQAGgDAEgEIACgFIABgIIACgKIAAgJIAAgMIABgQIAAgRIAAgRIAAg6IAAgLIgBgKIgCgIIgCgGQgFgGgGgCIgOgDIAAgDIAkAAIA6AAIATAAIASABIAUADQAKACAKAEQAMAGALAIQALAIAJAMQAIALAFAQQAFAPAAATQAAAWgFARQgGARgJAMQgJANgMAIQgNAIgNAFQgOAEgPACQgPACgNAAgAgmhmIgIABIgFABIgCApIAAA8IAAAjIAAAaIABAJIABAKIACAIIADAFQAGAGAJACIASACIAOgBIAOgDQAhgJAQgbQAQgbAAgmQABgRgGgRQgFgRgKgNQgKgNgNgJQgNgKgQgCIgMgDIgRAAIgIAAg");
	this.shape_29.setTransform(161.35,32.275);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("ABQBqIgvg2IgmgwIgmgqIgngsIAAB+IABAbQABAMADAGQADAHAIADQAGAEAMACIAAADIhJAAIAAgDIAOgEQAHgDAFgHQAEgGABgNIACgcIABgfIAAglIAAgOIAAgMIAAgLIAAgOQgBgJgEgFQgDgGgEgDQgFgDgFgCIgKgCIAAgCIA9AAICNCkIAAhlIAAgXQAAgKgDgGQgDgJgIgFQgHgGgOgCIAAgCIBKAAIAAACQgLACgHAEQgHAFgDAIQgCAEgBANIgCAZIgBAfIAAAlIAAATIAAAVIAAAXIAAATIgBACIgBABQgDgBgDgCg");
	this.shape_30.setTransform(135.35,32.35);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgrBmQgUgIgQgOQgPgPgIgUQgKgUABgZQAAgYAJgVQAJgUAQgPQAQgOAVgIQAVgHAXAAQAZAAAUAJQAVAJAOAPQAOAPAHAUQAIAUAAAVQgBAXgIAVQgJAUgQAPQgPAPgVAIQgVAIgWAAQgWAAgVgIgAghhfQgOAKgJAPQgKAPgEATQgEATAAASQAAAVAEATQAGATAJAOQAJAOAPAJQAOAJARAAQAUAAAOgKQANgKAKgPQAJgPAFgTQAFgSAAgTQAAgSgFgSQgFgTgJgPQgJgPgPgKQgOgJgTAAQgTAAgOAJg");
	this.shape_31.setTransform(110.05,32.225);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgsBsIAAgDIANgEQAHgDAEgEIADgGIABgIIABgJIAAgKIAAgLIAAgQIAAgSIAAgQIAAg6IAAgLIAAgKIgCgIIgCgGQgEgFgHgDIgOgDIAAgDIBZAAIAAADIgNADQgIACgDAIQgDAFAAAIIgBAOIAAAQIAAAOIAAAQIAAARIAABDIAAARQABAHACAEQAEAFAHADIAOADIAAADg");
	this.shape_32.setTransform(69.075,32.3);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("Ah0BsIAAgDQAHgBAIgDQAGgDAEgEIACgFIABgIIABgKIABgJIAAgMIABgQIAAgRIAAgRIAAg6IAAgLIgBgKIgCgIIgCgGQgFgGgGgCIgOgDIAAgDIAkAAIA6AAIATAAIATABIATADQAKACAKAEQAMAGAMAIQALAIAIAMQAIALAFAQQAFAPAAATQAAAWgFARQgFARgKAMQgKANgLAIQgNAIgNAFQgOAEgPACQgPACgNAAgAglhmIgJABIgFABIgCApIAAA8IAAAjIAAAaIABAJIABAKIACAIIADAFQAGAGAJACIASACIAOgBIAPgDQAggJAQgbQAQgbAAgmQAAgRgFgRQgFgRgKgNQgKgNgNgJQgNgKgQgCIgMgDIgRAAIgIAAg");
	this.shape_33.setTransform(50.55,32.275);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AAbBuIAAgDIAFgBIAHgBIAHgFQACgCAAgFIgBgIIgFgPIgHgUIgIgXIhPAAIgJAWIgIAVQgGAQAAAGQAAAEACADIAGAFIAIACIAJABIAAADIhAAAIAAgEQAHAAAGgDIAHgFIAGgKIAMgXIAOggIAQgkIARgnIAPgkIgDgGIAKgGIAHgHIAFgGIADgGIADAAIARAvIAQArIAPAnIAPAnIAGAPIAGAOIADAEIAFAGIAJAGQAFACAHAAIAAAEgAAYAVIgKgaIgKgaIgIgXIgHgRIgFANIgJAUIgLAbIgNAgIBJAAg");
	this.shape_34.setTransform(27.075,32.1);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AAdBsIAAgDQALgBAHgDQAIgDACgEIABgDIABgHIABgIIAAgHIAAgVIAAgTIAAgRIAAgLIh2AAIAABBIABARQAAAHADAEQADAFAHADQAHADAFAAIAAADIhYAAIAAgDIAOgEQAIgDADgEIACgFIACgIIAAgKIABgKIAAgLIAAgQIAAgSIAAgQIAAg7IAAgKIAAgKIgCgIIgDgHQgEgEgGgDIgOgDIAAgDIBaAAIAAADIgJACIgJAEQgEACgDAEQgDAFAAAHIgBAWIAAAYIAAATIAAALIB2AAIAAgRIAAgQIAAgPIAAgSIgBgMQAAgFgDgFQgFgHgHgDIgOgCIAAgDIBaAAIAAADQgGABgIADQgHADgDAGIgCAGIgBAIIAAAKIAAAJIAAA0IAAASIAAASIAAASIAAATIABAQQABAIABACQAEAGAHADIAOADIAAADg");
	this.shape_35.setTransform(150.25,4.6);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AgyBtIAAgCIAPgEQAHgBAHgJIADgEIABgIIAAgJIABgKIAAgLIAAgQIAAgRIAAgSIAAhiIgLAAIgJAAIgIAAIgKAAQgLABgIACQgHADgHAGIgFAGIgGAJIgIALIgFALIgCgBIAJg5IANACIAQABIAVABIASAAIARAAIATAAIAUAAIARAAIARAAIAUgBIARgBIANgDIAKA6IgDABIgFgMIgHgKIgHgKIgGgHQgGgFgHgCQgIgCgLgBIgKAAIgIAAIgJAAIgLAAIAAAUIAAAbIAAAcIAAAXIAABCIAAAQQAAAJADADQAFAGAHADIAQAEIAAACg");
	this.shape_36.setTransform(125.85,4.45);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10,p:{x:197.275}},{t:this.shape_9},{t:this.shape_8,p:{x:124.775}},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5,p:{x:197.675}},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10,p:{x:197.275}},{t:this.shape_26,p:{x:66.275}},{t:this.shape_25,p:{x:82.475}},{t:this.shape_24},{t:this.shape_23},{t:this.shape_5,p:{x:149.975}},{t:this.shape_22},{t:this.shape_21,p:{x:201.975}},{t:this.shape_20},{t:this.shape_19,p:{x:240.175}},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},1).to({state:[{t:this.shape_36},{t:this.shape_35},{t:this.shape_10,p:{x:175.025}},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_26,p:{x:87.675}},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_8,p:{x:184.525}},{t:this.shape_28},{t:this.shape_27},{t:this.shape_25,p:{x:253.475}},{t:this.shape_21,p:{x:265.425}},{t:this.shape_19,p:{x:277.375}},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},1).wait(1));

	// headline
	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgLANQgGgFAAgIQAAgGAGgGQAFgFAGAAQAIAAAFAGQAFAFAAAHQAAAIgFAEQgFAFgIAAQgGAAgFgFg");
	this.shape_37.setTransform(196.425,69.075);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AgyBuIAAgEIAPgDQAHgCAHgHIADgGIABgHIAAgKIAAgKIAAgLIABgPIAAgSIAAgQIAAhiIgLAAIgJAAIgIAAIgKAAQgMAAgHADQgHACgHAGIgFAGIgGAJIgIALIgEALIgDgBIAJg5IANADIARABIAUAAIASAAIARAAIATAAIATAAIASAAIARAAIAUAAIARgCIAOgEIAJA7IgDABIgFgLIgHgMIgHgJIgFgGQgHgHgHgBQgIgCgLAAIgKAAIgIAAIgJAAIgLAAIAAAUIAAAbIAAAcIAAAWIAABCIAAARQAAAHADAEQAFAHAHACIAPADIAAAEg");
	this.shape_38.setTransform(181.75,59.85);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AgrBmQgUgIgQgOQgPgPgIgUQgJgUAAgZQAAgYAJgVQAJgUAQgPQAQgOAVgIQAVgHAXAAQAZAAAUAJQAVAJANAPQAPAPAHAUQAIAUAAAVQgBAXgIAVQgJAUgQAPQgPAPgVAIQgUAIgXAAQgWAAgVgIgAghhfQgOAKgJAPQgKAPgEATQgEATAAASQAAAVAEATQAGATAJAOQAKAOAOAJQAOAJARAAQAUAAAOgKQANgKAKgPQAJgPAFgTQAFgSAAgTQAAgSgFgSQgFgTgKgPQgIgPgPgKQgOgJgTAAQgTAAgOAJg");
	this.shape_39.setTransform(158.55,59.925);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AgrBmQgUgIgQgOQgPgPgIgUQgKgUABgZQAAgYAJgVQAJgUAQgPQAQgOAVgIQAVgHAXAAQAZAAAUAJQAVAJAOAPQAOAPAHAUQAIAUAAAVQgBAXgIAVQgJAUgQAPQgPAPgVAIQgVAIgWAAQgWAAgVgIgAghhfQgOAKgJAPQgKAPgEATQgEATAAASQAAAVAEATQAGATAJAOQAJAOAPAJQAOAJARAAQAUAAANgKQAOgKAKgPQAJgPAFgTQAFgSAAgTQAAgSgFgSQgFgTgJgPQgJgPgPgKQgOgJgTAAQgTAAgOAJg");
	this.shape_40.setTransform(134.35,59.925);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("AhgBsIAAgDIAPgEQAGgCAFgFIACgGIACgIIABgJIAAgJIAAgMIABgQIAAgSIAAgQIAAgQIAAgNIAAgOIgBgPIAAgMIgBgKIgCgJIgDgGQgEgEgFgCIgMgDIAAgDIBkAAIAWABQAKABAKAEQAPAGAKAMQAKAMAAARQAAAUgNANQgNAMgUADIAAACQALABAKADQALAEAIAHQAIAHAFAJQAFAKAAAMQAAAKgDAKQgEAIgFAGQgFAIgHAEQgHAFgGACQgMAEgOABIgbABgAggATIAAASIAAAQIABAMIABASQAAAIAEAFQADADAFACQAGADAKAAIASgBQAKgCAJgFQANgGAHgLQAHgLAAgQQAAgJgDgHQgDgIgFgGQgFgGgGgGQgHgEgIgCIgNgEIgPAAIgdAAgAgVhmIgIABIgBADIAAAEIgBAFIAAAJIgBAYIAAAXIAAAUIAAAJIARAAIALAAQAagBAOgOQAOgOAAgVQAAgOgIgNQgHgLgMgFQgNgGgUAAg");
	this.shape_41.setTransform(110.725,60);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FFFFFF").s().p("AhiBsIAAgDIANgEQAHgDAEgEIADgGIABgIIABgJIABgKIAAgLIAAgQIAAgSIAAgQIAAg6IAAgLIgBgMIgBgJIgDgFQgEgFgFgCIgOgCIAAgDIClAAIAUAyIgDABQgYgfgVgKQgFgCgOgCQgOgCgTAAIgNABIgKAAIgBAUIAAAjIAAATIAAANIAAAIIAAADIAGAAIALAAIALgBIAJgBQAJgCAGgEQAGgEAEgFIAGgLIAEgQIADAAIAABeIgDAAQgDgKgFgKQgFgKgFgFQgFgEgHgDQgGgDgIgBIgIAAIgGAAIgGAAIgIAAIAAANIAAAQIAAAJIAAAKIAAAKIAAAHIABASQABAJADADQACAFALACQAKACALAAIANgBIAQgBQAKgBAIgEQAIgEAIgGQAHgGAHgJIAPgWIADAAIgPA6g");
	this.shape_42.setTransform(197.675,32.3);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FFFFFF").s().p("AgrBmQgUgIgQgOQgPgPgIgUQgKgUABgZQAAgYAJgVQAJgUAQgPQAQgOAVgIQAVgHAXAAQAZAAAUAJQAVAJAOAPQAOAPAHAUQAIAUAAAVQgBAXgIAVQgJAUgQAPQgPAPgVAIQgVAIgWAAQgWAAgVgIgAghhfQgOAKgJAPQgKAPgEATQgEATAAASQAAAVAEATQAGATAJAOQAJAOAPAJQAOAJARAAQAUAAANgKQAOgKAKgPQAJgPAFgTQAFgSAAgTQAAgSgFgSQgFgTgJgPQgJgPgPgKQgOgJgTAAQgTAAgOAJg");
	this.shape_43.setTransform(174.4,32.225);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#FFFFFF").s().p("AAdBsIAAgDQALgBAHgDQAIgDACgEIABgEIABgGIAAgHIABgIIAAgUIAAgUIAAgRIAAgLIh2AAIAABBIABARQAAAHADAEQADAFAHADQAHADAFAAIAAADIhYAAIAAgDIAPgEQAGgDAEgEIACgFIABgIIABgKIABgKIAAgLIAAgQIAAgSIAAgQIAAg6IAAgLIAAgKIgCgIIgDgGQgEgFgGgDIgOgDIAAgDIBZAAIAAADIgJACIgIADQgEADgDAEQgCAFgBAHIgBAXIAAAXIAAATIAAALIB2AAIAAgRIAAgQIAAgPIAAgSIgBgMQAAgGgDgEQgFgHgHgDIgOgCIAAgDIBaAAIAAADQgGABgIADQgGADgEAGIgCAGIgBAJIAAAJIAAAJIAAA0IAAATIAAARIAAASIAAATIABAQQABAIABADQAEAGAHACIAOADIAAADg");
	this.shape_44.setTransform(148.7,32.3);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#FFFFFF").s().p("AAbBuIAAgDIAFgBIAHgBIAHgFQACgCAAgFIgBgIIgFgPIgHgUIgIgXIhPAAIgJAWIgIAVQgGAQAAAGQAAAEACADIAGAFIAIACIAJABIAAADIhAAAIAAgEQAHAAAGgDIAHgFIAGgKIAMgXIAOggIAQgkIARgnIAPgkIgDgGIAKgGIAHgHIAFgGIADgGIADAAIARAvIAQArIAPAnIAPAnIAGAPIAGAOIADAEIAFAGIAJAGQAFACAHAAIAAAEgAAYAVIgKgaIgKgaIgIgXIgHgRIgFANIgJAUIgLAbIgNAgIBJAAg");
	this.shape_45.setTransform(124.775,32.1);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#FFFFFF").s().p("AgyBuIAAgDIAPgEQAHgBAHgJIADgEIAAgIIABgJIAAgKIAAgMIABgPIAAgRIAAgRIAAhiIgLAAIgJAAIgIAAIgKAAQgLAAgIACQgHADgHAGIgFAGIgHAJIgHALIgEALIgDgBIAJg5IANADIARAAIAUABIARAAIASAAIATAAIATAAIASAAIARAAIAUgBIARgBIAOgDIAJA6IgCABIgGgLIgHgLIgHgKIgFgGQgHgHgIgBQgGgCgMAAIgKAAIgJAAIgIAAIgLAAIAAATIAAAcIAAAbIAAAXIAABCIAAARQABAHACAEQAEAGAJADIAOAEIAAADg");
	this.shape_46.setTransform(103.2,32.15);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#FFFFFF").s().p("AhiBsIAAgDIANgEQAHgDAEgFIADgFIABgHIABgKIABgKIAAgLIAAgQIAAgSIAAgQIAAg7IAAgKIgBgLIgBgJIgDgGQgEgFgFgCIgOgCIAAgDIClAAIAUAxIgDACQgYgegVgLQgFgCgOgCQgOgCgTAAIgNAAIgKABIgBAUIAAAjIAAATIAAANIAAAIIAAADIAGAAIALAAIALgBIAJgBQAJgDAGgDQAGgEAEgFIAGgLIAEgQIADAAIAABeIgDAAQgDgKgFgKQgFgKgFgFQgFgFgHgCQgGgDgIAAIgIgBIgGAAIgGAAIgIAAIAAAMIAAARIAAAJIAAAKIAAAJIAAAIIABASQABAJADADQACAFALACQAKABALAAIANAAIAQgBQAKgCAIgDQAIgDAIgHQAHgGAHgJIAPgWIADAAIgPA6g");
	this.shape_47.setTransform(197.275,4.6);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#FFFFFF").s().p("AAdBsIAAgDQALgBAHgDQAIgDADgEIABgDIAAgHIABgIIAAgHIAAgVIAAgTIAAgRIAAgLIh1AAIAABBIAAARQAAAHACAEQAEAFAHADQAGADAHAAIAAADIhZAAIAAgDIAOgEQAIgDADgEIACgFIACgIIAAgKIAAgKIAAgLIABgQIAAgSIAAgQIAAg7IAAgKIgBgKIgBgIIgCgHQgFgEgGgDIgOgDIAAgDIBaAAIAAADIgJACIgJAEQgEACgDAEQgDAFAAAHIAAAWIAAAYIAAATIAAALIB1AAIAAgRIAAgQIAAgPIAAgSIgBgMQgBgFgCgFQgFgHgHgDIgOgCIAAgDIBbAAIAAADQgIABgHADQgGADgEAGIgBAGIgBAIIgBAKIAAAJIAAA0IAAASIAAASIAAASIABATIAAAQQAAAIACACQAEAGAGADIAPADIAAADg");
	this.shape_48.setTransform(172.5,4.6);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#FFFFFF").s().p("AgyBtIAAgCIAPgEQAHgBAHgJIADgEIABgIIAAgJIAAgKIAAgLIABgQIAAgRIAAgSIAAhiIgLAAIgJAAIgIAAIgKAAQgLABgIACQgHADgHAGIgFAGIgHAJIgHALIgEALIgDgBIAJg5IANACIARABIAUABIASAAIARAAIATAAIATAAIASAAIARAAIAUgBIARgBIAOgDIAJA6IgDABIgFgMIgHgKIgHgKIgFgHQgHgFgIgCQgHgCgLgBIgKAAIgJAAIgIAAIgLAAIAAAUIAAAbIAAAcIAAAXIAABCIAAAQQAAAJADADQAEAGAJADIAOAEIAAACg");
	this.shape_49.setTransform(148.1,4.45);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#FFFFFF").s().p("ABQBqIgvg2IgmgvIgmgrIgngsIAAB+IABAbQABAMADAGQADAHAIADQAGAEANACIAAACIhKAAIAAgCIAOgEQAHgDAFgHQAEgGABgNIACgcIABgfIAAglIAAgOIAAgLIAAgMIAAgOQgBgJgEgGQgCgFgFgDQgFgEgFAAIgKgDIAAgDIA9AAICNCmIAAhmIgBgWQAAgLgCgGQgDgJgHgFQgIgFgOgDIAAgDIBKAAIAAADQgMACgGAEQgHAEgDAJQgCAEgBANIgCAZIgBAfIAAAlIAAATIAAAVIAAAXIAAATIgBABIgBABQgDAAgDgCg");
	this.shape_50.setTransform(117.7,4.65);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#FFFFFF").s().p("AgsBsIAAgDIANgEQAHgDAEgFIADgFIABgHIABgKIAAgKIAAgLIAAgQIAAgSIAAgQIAAg7IAAgKIAAgKIgCgIIgCgHQgEgEgHgDIgOgDIAAgDIBZAAIAAADIgNADQgIACgDAIQgDAFAAAIIgBAOIAAAPIAAAPIAAAQIAAARIAABDIAAARQABAHACAEQAEAFAHADIAOADIAAADg");
	this.shape_51.setTransform(98.475,4.6);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#FFFFFF").s().p("AAbBuIAAgDIAFgBIAHgCIAHgEQACgCAAgFIgBgJIgFgPIgHgUIgIgWIhPAAIgJAWIgIAVQgGAQAAAHQAAADACADIAGAEIAIACIAJACIAAADIhAAAIAAgEQAHAAAGgEIAHgEIAGgKIAMgXIAOggIAQgkIARgmIAPgkIgDgIIAKgFIAHgHIAFgHIADgFIADAAIARAvIAQArIAPAnIAPAmIAGAQIAGANIADAFIAFAGIAJAFQAFADAHAAIAAAEgAAYAVIgKgaIgKgaIgIgXIgHgRIgFAMIgJAVIgLAbIgNAgIBJAAg");
	this.shape_52.setTransform(183.275,-23.3);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#FFFFFF").s().p("AhlBsIAAgDIAPgEQAHgDAEgFIADgEIACgIIABgKIAAgJIAAgMIABgQIAAgRIAAgRIAAg6IAAgLIgBgKIgBgIIgDgGQgEgEgHgDQgHgDgIgBIAAgDIBgAAIAAADIgKACIgKAEQgFACgDAGQgDAFgBAHIAAATIgBARIAAASIAAAUIAAASIAAAPIAAARIABASIAAASQABAJADAEIAEAEIAJACIALABIALABIAIAAIALgBIANgBIAMgCQAMgEAIgEQAIgGAGgHQAFgHAEgIIAIgRIADAAIgMA+g");
	this.shape_53.setTransform(162.725,-23.1);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#FFFFFF").s().p("AgqBmQgVgIgPgOQgQgPgIgUQgKgUABgZQAAgYAJgVQAJgUAQgPQAQgOAVgIQAVgHAXAAQAZAAAUAJQAVAJAOAPQAOAPAHAUQAHAUABAVQAAAXgJAVQgJAUgQAPQgPAPgVAIQgVAIgWAAQgWAAgUgIgAghhfQgOAKgKAPQgJAPgEATQgEATAAASQAAAVAFATQAEATAKAOQAJAOAPAJQAOAJARAAQAUAAANgKQAPgKAJgPQAJgPAFgTQAEgSABgTQgBgSgEgSQgFgTgJgPQgJgPgPgKQgOgJgTAAQgTAAgOAJg");
	this.shape_54.setTransform(139.4,-23.175);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#FFFFFF").s().p("AhlBsIAAgDIAPgEQAHgDAEgFIADgEIACgIIABgKIAAgJIAAgMIABgQIAAgRIAAgRIAAg6IAAgLIgBgKIgBgIIgDgGQgEgEgHgDQgHgDgIgBIAAgDIBgAAIAAADIgKACIgKAEQgFACgDAGQgDAFgBAHIAAATIgBARIAAASIAAAUIAAASIAAAPIAAARIABASIAAASQABAJADAEIAEAEIAJACIALABIALABIAIAAIALgBIANgBIAMgCQAMgEAIgEQAIgGAGgHQAFgHAEgIIAIgRIADAAIgMA+g");
	this.shape_55.setTransform(117.325,-23.1);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#FFFFFF").s().p("AgsBsIAAgDIANgEQAHgDAEgEIADgGIABgIIABgJIAAgKIAAgLIAAgQIAAgSIAAgQIAAg6IAAgLIAAgKIgCgIIgCgGQgEgFgHgDIgOgDIAAgDIBZAAIAAADIgNADQgIACgDAIQgDAFAAAIIgBAOIAAAQIAAAOIAAAQIAAARIAABDIAAARQABAHACAEQAEAFAHADIAOADIAAADg");
	this.shape_56.setTransform(240.175,32.3);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#FFFFFF").s().p("ABQBqIgug2IgngwIgmgqIgngsIAAB+IABAbQABAMADAGQADAHAIADQAGAEANACIAAADIhKAAIAAgDIAOgEQAHgDAFgHQAEgGABgNIACgcIABgfIAAglIAAgOIAAgMIAAgLIAAgOQgBgJgEgFQgCgGgFgDQgFgDgFgCIgKgCIAAgCIA9AAICNCkIAAhlIgBgXQAAgKgCgGQgDgJgIgFQgHgGgOgCIAAgCIBKAAIAAACQgMACgGAEQgHAFgDAIQgCAEgBANIgCAZIgBAfIAAAlIAAATIAAAVIAAAXIAAATIgBACIgBABQgDgBgDgCg");
	this.shape_57.setTransform(221.2,32.35);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#FFFFFF").s().p("AgsBsIAAgDIANgEQAHgDAEgEIADgGIABgIIABgJIAAgKIAAgLIAAgQIAAgSIAAgQIAAg6IAAgLIAAgKIgCgIIgCgGQgEgFgHgDIgOgDIAAgDIBZAAIAAADIgNADQgIACgDAIQgDAFAAAIIgBAOIAAAQIAAAOIAAAQIAAARIAABDIAAARQABAHACAEQAEAFAHADIAOADIAAADg");
	this.shape_58.setTransform(201.975,32.3);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#FFFFFF").s().p("AAmBsIAAgDQAMgBAJgFQAIgFAEgGIADgKIABgLIAAgmIAAglIAAhVIgSAqIgRAkIgQAjIgSAoIgEAKIgFANIgEAMIgEAIIgCAAIgTgsIgSgrIgRglIgNgfIgLgXIgFgMIgBAiIAAAfIAAAeIAAAmIABAYQABALADAHQAEAHAHAEQAIAEANACIAAADIhPAAIAAgDQAKgCAHgEQAGgEAEgIQAFgHACgKIABgaIABgeIAAglIAAgPIAAgLIAAgMIAAgPQAAgIgDgGQgDgFgFgDIgJgEIgJgCIAAgDIA/AAIBHCjIAag5IAWgyIARgnIAIgRIA/AAIAAADQgMAAgGAFQgHAFgCAHQgCAFAAAKIgBAWIgBAcIAAAaIAAAgIABAiIABALIACAJIACAEIAGAEIAJAFQAFACAHAAIAAADg");
	this.shape_59.setTransform(181.1,32.3);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#FFFFFF").s().p("AgsBnQgWgHgQgOQgPgOgIgVQgIgVAAgZIABgQQABgKAEgLQAEgLAHgLQAHgLAJgKQAPgOAVgIQAVgJAdAAQASAAAOADQANADAKAEIAPAHIAFADIAEgEIAGgIIADAAIAABBIgEAAQgDgNgHgMQgHgMgGgIQgLgKgPgGQgPgHgSAAQgSAAgRAJQgQAJgLAPQgKAPgHATQgFATAAAVQgBAXAGATQAFAUALANQAMAOAPAIQAQAIASAAQAPAAAMgFQANgFAHgLQADgEABgKIABgVIgBgTQgBgIgGgFQgGgIgSgCIAAgDIBYAAIAAADIgLADQgGACgCAEQgCADgBAHIAAAOIAAAsIgLAGIgUAIQgMAFgOADQgOADgPAAQgbAAgXgIg");
	this.shape_60.setTransform(126.35,32.175);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#FFFFFF").s().p("Ah0BsIAAgDQAIgBAGgDQAIgDADgEIACgFIACgIIAAgKIABgJIAAgMIAAgQIAAgRIAAgRIAAg6IAAgLIAAgKIgBgIIgDgGQgFgGgGgCIgOgDIAAgDIAlAAIA4AAIAUAAIATABIAUADQAKACAJAEQAMAGAMAIQAKAIAJAMQAIALAFAQQAFAPAAATQAAAWgFARQgGARgJAMQgKANgMAIQgMAIgOAFQgNAEgPACQgPACgNAAgAgmhmIgHABIgGABIgBApIgBA8IAAAjIABAaIAAAJIABAKIACAIIADAFQAGAGAJACIARACIAPgBIAOgDQAhgJAQgbQARgbAAgmQAAgRgGgRQgFgRgKgNQgKgNgNgJQgOgKgPgCIgMgDIgSAAIgIAAg");
	this.shape_61.setTransform(101.45,32.275);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#FFFFFF").s().p("AgsBsIAAgDIANgEQAHgDAEgEIADgGIABgIIABgJIAAgKIAAgLIAAgQIAAgSIAAgQIAAg6IAAgLIAAgKIgCgIIgCgGQgEgFgHgDIgOgDIAAgDIBZAAIAAADIgNADQgIACgDAIQgDAFAAAIIgBAOIAAAQIAAAOIAAAQIAAARIAABDIAAARQABAHACAEQAEAFAHADIAOADIAAADg");
	this.shape_62.setTransform(82.475,32.3);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#FFFFFF").s().p("AA0BsIgEgEIgDgDIgDgFIgHgLIgLgPIgIgNIgKgNIgMgQIgNgMQgHgGgHgCIgJgBIgHAAIAAAhIAAAZIABAQQAAAHADAFQACAEAHAEQAHAEANAAIAAADIhgAAIAAgDIAOgDQAHgDAEgFIACgFIACgIIAAgKIABgJIAAgMIAAgQIAAgRIAAgRIAAg6IAAgLIgBgLIgBgJIgDgGQgEgEgGgCIgOgDIAAgDIANAAIAXAAIAaAAIAUAAIAjABQAQABANAHQANAHAIAMQAIAMAAASQAAALgEAJQgEAJgHAGQgGAHgKAFIgSAHIAAABQAFADAFAFIAJALIARAZIAQAXQALAQALAHQAKAHAOACIAAADgAgphmIgGAAIAAAEIgBADIAAAGIgBAKIAAAYIAAAaIAAAVIAAALIAXgBQALgBAJgDQAJgDAHgFQAHgFAEgGQAEgHADgHQACgIAAgIQAAgPgIgMQgHgLgPgHIgOgFIgRgCg");
	this.shape_63.setTransform(66.275,32.275);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#FFFFFF").s().p("AAvBsIgDgCIgDgDIglgqIgjgoIgKgLIgFgCIgDABIgCAEIAAAdIAAAYIACAQQAAAHADAFIAGAEIAIAEIAIACIAHABIAAADIhgAAIAAgDIAOgDQAHgDAEgEIACgGIACgIIAAgKIAAgKIABgLIAAgQIAAgSIAAgQIAAg6IgBgWQgBgJgDgEQgEgFgGgDIgOgDIAAgDIBdAAIAAADIgLACQgGABgEADQgEADgDAIQgDAGAAANIgBANIAAAOIAAATIAAAaIAPgKIATgSIATgVIARgSIAJgMQAEgGAAgFQAAgJgGgEQgGgEgIgBIAAgDIBRAAIAAADQgPABgQAMQgQAMgQAOIgNAMIgNAOIgLAMIgMAMIAMANIATAXIAaAdIAaAdIAHAHIAIAHIAGAEIAEADIAKADIAPACIAAADg");
	this.shape_64.setTransform(231.025,32.3);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#FFFFFF").s().p("AghBnQgXgIgPgPQgQgOgIgUQgJgUAAgZIABgLIADgPIAFgQIAJgRQAGgLAJgJQAKgJAMgHQANgHAQgFQAQgEASAAQATAAANAEQAOADAJAEIANAHIAGADIACgBIAEgDIAEgFIADgFIAEAAIAABDIgEAAQgEgOgIgNQgHgMgLgKQgLgJgNgFQgNgGgPAAQgUAAgQAKQgQAJgLAPQgLAPgGAUQgGATAAAUQAAAVAGATQAGATAMAOQALAOAQAIQAQAIATAAQAQAAAOgFQANgGALgKQAKgJAIgMQAHgMADgNIAEAAIgBBCIgEAAIgHgJQgEgFgCAAIgFAEIgOAHQgJADgNADQgNADgRAAQgbAAgWgIg");
	this.shape_65.setTransform(206.375,32.125);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#FFFFFF").s().p("Ah0BsIAAgDQAHgBAIgDQAGgDAEgEIACgFIABgIIACgKIAAgJIAAgMIABgQIAAgRIAAgRIAAg6IAAgLIgBgKIgCgIIgCgGQgFgGgGgCIgOgDIAAgDIAkAAIA6AAIATAAIASABIAUADQAKACAKAEQAMAGALAIQALAIAJAMQAIALAFAQQAFAPAAATQAAAWgFARQgGARgJAMQgJANgMAIQgNAIgNAFQgOAEgPACQgPACgNAAgAgmhmIgIABIgFABIgCApIAAA8IAAAjIAAAaIABAJIABAKIACAIIADAFQAGAGAJACIASACIAOgBIAOgDQAhgJAQgbQAQgbAAgmQABgRgGgRQgFgRgKgNQgKgNgNgJQgNgKgQgCIgMgDIgRAAIgIAAg");
	this.shape_66.setTransform(161.35,32.275);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("#FFFFFF").s().p("ABQBqIgvg2IgmgwIgmgqIgngsIAAB+IABAbQABAMADAGQADAHAIADQAGAEAMACIAAADIhJAAIAAgDIAOgEQAHgDAFgHQAEgGABgNIACgcIABgfIAAglIAAgOIAAgMIAAgLIAAgOQgBgJgEgFQgDgGgEgDQgFgDgFgCIgKgCIAAgCIA9AAICNCkIAAhlIAAgXQAAgKgDgGQgDgJgIgFQgHgGgOgCIAAgCIBKAAIAAACQgLACgHAEQgHAFgDAIQgCAEgBANIgCAZIgBAfIAAAlIAAATIAAAVIAAAXIAAATIgBACIgBABQgDgBgDgCg");
	this.shape_67.setTransform(135.35,32.35);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f("#FFFFFF").s().p("AgrBmQgUgIgQgOQgPgPgIgUQgKgUABgZQAAgYAJgVQAJgUAQgPQAQgOAVgIQAVgHAXAAQAZAAAUAJQAVAJAOAPQAOAPAHAUQAIAUAAAVQgBAXgIAVQgJAUgQAPQgPAPgVAIQgVAIgWAAQgWAAgVgIgAghhfQgOAKgJAPQgKAPgEATQgEATAAASQAAAVAEATQAGATAJAOQAJAOAPAJQAOAJARAAQAUAAAOgKQANgKAKgPQAJgPAFgTQAFgSAAgTQAAgSgFgSQgFgTgJgPQgJgPgPgKQgOgJgTAAQgTAAgOAJg");
	this.shape_68.setTransform(110.05,32.225);

	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.f("#FFFFFF").s().p("AgsBsIAAgDIANgEQAHgDAEgEIADgGIABgIIABgJIAAgKIAAgLIAAgQIAAgSIAAgQIAAg6IAAgLIAAgKIgCgIIgCgGQgEgFgHgDIgOgDIAAgDIBZAAIAAADIgNADQgIACgDAIQgDAFAAAIIgBAOIAAAQIAAAOIAAAQIAAARIAABDIAAARQABAHACAEQAEAFAHADIAOADIAAADg");
	this.shape_69.setTransform(69.075,32.3);

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.f("#FFFFFF").s().p("Ah0BsIAAgDQAHgBAIgDQAGgDAEgEIACgFIABgIIABgKIABgJIAAgMIABgQIAAgRIAAgRIAAg6IAAgLIgBgKIgCgIIgCgGQgFgGgGgCIgOgDIAAgDIAkAAIA6AAIATAAIATABIATADQAKACAKAEQAMAGAMAIQALAIAIAMQAIALAFAQQAFAPAAATQAAAWgFARQgFARgKAMQgKANgLAIQgNAIgNAFQgOAEgPACQgPACgNAAgAglhmIgJABIgFABIgCApIAAA8IAAAjIAAAaIABAJIABAKIACAIIADAFQAGAGAJACIASACIAOgBIAPgDQAggJAQgbQAQgbAAgmQAAgRgFgRQgFgRgKgNQgKgNgNgJQgNgKgQgCIgMgDIgRAAIgIAAg");
	this.shape_70.setTransform(50.55,32.275);

	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.f("#FFFFFF").s().p("AAbBuIAAgDIAFgBIAHgBIAHgFQACgCAAgFIgBgIIgFgPIgHgUIgIgXIhPAAIgJAWIgIAVQgGAQAAAGQAAAEACADIAGAFIAIACIAJABIAAADIhAAAIAAgEQAHAAAGgDIAHgFIAGgKIAMgXIAOggIAQgkIARgnIAPgkIgDgGIAKgGIAHgHIAFgGIADgGIADAAIARAvIAQArIAPAnIAPAnIAGAPIAGAOIADAEIAFAGIAJAGQAFACAHAAIAAAEgAAYAVIgKgaIgKgaIgIgXIgHgRIgFANIgJAUIgLAbIgNAgIBJAAg");
	this.shape_71.setTransform(27.075,32.1);

	this.shape_72 = new cjs.Shape();
	this.shape_72.graphics.f("#FFFFFF").s().p("AAdBsIAAgDQALgBAHgDQAIgDACgEIABgDIABgHIABgIIAAgHIAAgVIAAgTIAAgRIAAgLIh2AAIAABBIABARQAAAHADAEQADAFAHADQAHADAFAAIAAADIhYAAIAAgDIAOgEQAIgDADgEIACgFIACgIIAAgKIABgKIAAgLIAAgQIAAgSIAAgQIAAg7IAAgKIAAgKIgCgIIgDgHQgEgEgGgDIgOgDIAAgDIBaAAIAAADIgJACIgJAEQgEACgDAEQgDAFAAAHIgBAWIAAAYIAAATIAAALIB2AAIAAgRIAAgQIAAgPIAAgSIgBgMQAAgFgDgFQgFgHgHgDIgOgCIAAgDIBaAAIAAADQgGABgIADQgHADgDAGIgCAGIgBAIIAAAKIAAAJIAAA0IAAASIAAASIAAASIAAATIABAQQABAIABACQAEAGAHADIAOADIAAADg");
	this.shape_72.setTransform(150.25,4.6);

	this.shape_73 = new cjs.Shape();
	this.shape_73.graphics.f("#FFFFFF").s().p("AgyBtIAAgCIAPgEQAHgBAHgJIADgEIABgIIAAgJIABgKIAAgLIAAgQIAAgRIAAgSIAAhiIgLAAIgJAAIgIAAIgKAAQgLABgIACQgHADgHAGIgFAGIgGAJIgIALIgFALIgCgBIAJg5IANACIAQABIAVABIASAAIARAAIATAAIAUAAIARAAIARAAIAUgBIARgBIANgDIAKA6IgDABIgFgMIgHgKIgHgKIgGgHQgGgFgHgCQgIgCgLgBIgKAAIgIAAIgJAAIgLAAIAAAUIAAAbIAAAcIAAAXIAABCIAAAQQAAAJADADQAFAGAHADIAQAEIAAACg");
	this.shape_73.setTransform(125.85,4.45);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47,p:{x:197.275}},{t:this.shape_46},{t:this.shape_45,p:{x:124.775}},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42,p:{x:197.675}},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37}]}).to({state:[{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47,p:{x:197.275}},{t:this.shape_63,p:{x:66.275}},{t:this.shape_62,p:{x:82.475}},{t:this.shape_61},{t:this.shape_60},{t:this.shape_42,p:{x:149.975}},{t:this.shape_59},{t:this.shape_58,p:{x:201.975}},{t:this.shape_57},{t:this.shape_56,p:{x:240.175}},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37}]},1).to({state:[{t:this.shape_73},{t:this.shape_72},{t:this.shape_47,p:{x:175.025}},{t:this.shape_71},{t:this.shape_70},{t:this.shape_69},{t:this.shape_63,p:{x:87.675}},{t:this.shape_68},{t:this.shape_67},{t:this.shape_66},{t:this.shape_45,p:{x:184.525}},{t:this.shape_65},{t:this.shape_64},{t:this.shape_62,p:{x:253.475}},{t:this.shape_58,p:{x:265.425}},{t:this.shape_56,p:{x:277.375}},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37}]},1).wait(1));

	// logo
	this.shape_74 = new cjs.Shape();
	this.shape_74.graphics.f("#FFFFFF").s().p("AimC8QhUhDAAh5QAAhwBKhCQBHg/B1AAQAkAAAiAHQAjAIAoASQAYAKAKAAQAHAAAJgIIAJAFIgzBvIgKgEQAAgFgCgFIgDgHQgCgGgKgHQgUgPglgLQglgLgiAAQhDAAguApQgyAvAABKQAABLAxAtQAtApBJAAQAkAAAkgIQAigKAagPIAAg/IhrAAQgKAAgFAFQgFAGgDALIgKAAIAAhsIAKAAQADAMAFAFQAFAEAKgBIDPAAIAAALQgLAEgFAFQgFAFAAALIAABhQAAAKAEAGQAGAFALAEIAAAIQh8BMh1AAQhoAAhDg2gAEFCUIgSgFIgGgCIAAhBIAAgDIAHAEQAJAFAKAEQAgAMAkgCQA9gDAfgQQAQgIADgIIAAgvIhTAAQgIAAgEADQgEAEgCAKIgIAAIAAhSIAIAAQADAKADADQAEAEAIAAIChAAIAAAIQgKADgDAEQgEAEABAHIAABHQAAAIADAFQADAEAKACIAAAGQgpAjg0ARQgtAPgxAAQgoAAgggHgAnbBrQgXgPgJgaQgJgZAAgkIAAi8QAAgIgDgEQgCgEgJgCIAAgIIBhAAIAAAIQgJACgDAEQgDAEAAAIIAACoQAAAdACANQADAOAIAKQAXAaA0AAQA1AAAVgaQAIgJACgPQADgOAAgcIAAioQAAgIgDgEQgCgEgJgCIAAgIIBbAAIAAAIQgIACgDAEQgEAEAAAIIAAAaQgaAfgNAoQgMAmAAAwQAAAfAEAYQADAbAKAWQglAdhRAAQhJAAgngagACHgIIgBgbQABgZADgQQAEgRADgEQACABAAAMIAXAHIA4h4IAHgDIAVgIQAmgLAtADIAdABQAPACALADQAaAFAhANQARAHAHAAQAEAAAIgGIAHADIgoBVIgHgEQAAgIgCgEQgCgDgHgGQgQgMgdgIQgdgIgaAAQg0AAgkAeQgoAlgBA3QAAAKABAQgAH0hmQgFgFAAgIQAAgHAFgFQAFgFAIgBQAIABAEAFQAGAFAAAHQAAAIgGAFQgEAFgIAAQgIAAgFgFgAH3h+QgFAFAAAGQAAAHAFAEQAEAEAGAAQAGAAAEgEQAFgEgBgHQABgGgFgFQgEgDgGAAQgGAAgEADgAIGhpIgFgJIgEAAIAAAJIgDAAIAAgUIAIAAQADAAACABQAAABABAAQAAABAAAAQAAABAAABQABAAAAABQgBAFgFAAIAHAJgAH9h0IAEAAIADgBIABgCQAAgDgDgBIgFAAg");
	this.shape_74.setTransform(149.95,123.2);

	this.timeline.addTween(cjs.Tween.get(this.shape_74).wait(3));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,-70,300,217.4);


(lib.bg_mc = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("A3bTiMAAAgnDMAu3AAAMAAAAnDg");
	this.shape.setTransform(25.0008,24.9977,0.1667,0.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.bg_mc, new cjs.Rectangle(0,0,50,50), null);


(lib.m_itemimage = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,0,0);


(lib.m_itemhit = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF00FF").s().dr(-140,-64,280,128);
	this.shape.setTransform(140,64);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,280,128);


(lib.m_ctatext = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgjA1IAAhpIBIAAIAAAQIg2AAIAAAcIA1AAIAAAPIg1AAIAAAeIA2AAIAAAQg");
	this.shape.setTransform(139.6,11.375);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAUA1IgXgoIgTAAIAAAoIgSAAIAAhpIAtAAQAQAAAKAJQAJAJAAAPQAAANgHAIQgHAIgLABIAaAqgAgWgCIAZAAQAIAAAFgFQAFgEAAgIQAAgIgFgEQgFgFgIAAIgZAAg");
	this.shape_1.setTransform(129.975,11.375);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgmAoQgQgQAAgYQAAgXAQgQQAPgPAXAAQAYAAAQAPQAPAQgBAXQABAYgPAQQgQAPgYAAQgXAAgPgPgAgZgbQgJALAAAQQAAARAJAKQAKAMAPAAQAQAAAKgMQAJgKAAgRQAAgQgJgLQgKgLgQAAQgPAAgKALg");
	this.shape_2.setTransform(118.5,11.375);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAkA1IAAhQIggBQIgHAAIghhQIAABQIgTAAIAAhpIAaAAIAdBGIAdhGIAbAAIAABpg");
	this.shape_3.setTransform(105.65,11.375);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAVA1IgVhNIgUBNIgUAAIgehpIAVAAIAUBRIAXhRIANAAIAXBRIAUhRIAVAAIgeBpg");
	this.shape_4.setTransform(87.475,11.375);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgkA1IAAhpIBIAAIAAAQIg1AAIAAAcIA0AAIAAAPIg0AAIAAAeIA1AAIAAAQg");
	this.shape_5.setTransform(75.75,11.375);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgIA1IAAhpIARAAIAABpg");
	this.shape_6.setTransform(68.825,11.375);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgLA1IgqhpIAWAAIAfBVIAghVIAWAAIgqBpg");
	this.shape_7.setTransform(61.275,11.375);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.m_ctatext, new cjs.Rectangle(0,0,200,23.5), null);


(lib.m_ctabutton = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().dr(-100,-20,200,40);
	this.shape.setTransform(100,20);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.m_ctabutton, new cjs.Rectangle(0,0,200,40), null);


(lib.cta_line = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().dr(-57,-0.5,114,1);
	this.shape.setTransform(44.7686,0.5,0.7851,1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.cta_line, new cjs.Rectangle(0,0,89.5,1), null);


(lib.bg_texture = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(3));

	// image
	this.instance = new lib.rain_plate_300x600();
	this.instance.parent = this;

	this.instance_1 = new lib.snow_plate_300x600();
	this.instance_1.parent = this;

	this.instance_2 = new lib.cold_plate_300x600();
	this.instance_2.parent = this;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_2}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,300,600);


(lib.m_day = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.day_txt.font = "10px ProximaNova-Light";
		this.temp_txt.font = "16px ProximaNova-Semibold";
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// icon container
	this.icon_mc = new lib.m_weathericons();
	this.icon_mc.name = "icon_mc";
	this.icon_mc.parent = this;
	this.icon_mc.setTransform(0,14);

	this.timeline.addTween(cjs.Tween.get(this.icon_mc).wait(1));

	// text
	this.temp_txt = new cjs.Text("90°", "16px 'Proxima Nova Semibold'");
	this.temp_txt.name = "temp_txt";
	this.temp_txt.textAlign = "center";
	this.temp_txt.lineHeight = 20;
	this.temp_txt.lineWidth = 36;
	this.temp_txt.parent = this;
	this.temp_txt.setTransform(15,47);

	this.day_txt = new cjs.Text("MON", "10px 'Proxima Nova Semibold'");
	this.day_txt.name = "day_txt";
	this.day_txt.textAlign = "center";
	this.day_txt.lineHeight = 14;
	this.day_txt.lineWidth = 26;
	this.day_txt.parent = this;
	this.day_txt.setTransform(15,2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.day_txt},{t:this.temp_txt}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.m_day, new cjs.Rectangle(-5,0,40,68.5), null);


(lib.m_productcta = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.line = new lib.cta_line();
	this.line.name = "line";
	this.line.parent = this;
	this.line.setTransform(50.05,21.5,1,1,0,0,0,44.8,0.5);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AARArIgRg/IgQA/IgQAAIgZhVIARAAIARBBIAShBIALAAIASBBIARhBIARAAIgZBVg");
	this.shape.setTransform(86.425,14.175);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgfAgQgMgNAAgTQAAgTAMgMQAMgNATAAQATAAANANQAMAMAAATQAAATgMANQgNANgTAAQgTAAgMgNgAgUgVQgIAIAAANQAAAOAIAIQAIAJAMAAQANAAAIgJQAIgIAAgOQAAgNgIgIQgIgJgNAAQgMAAgIAJg");
	this.shape_1.setTransform(73.225,14.175);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AAXArIgsg+IAAA+IgQAAIAAhVIAQAAIArA8IAAg8IAQAAIAABVg");
	this.shape_2.setTransform(61.175,14.175);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AggArIAAhVIAlAAQANAAAIAIQAHAHAAAMQAAALgHAHQgIAIgNAAIgWAAIAAAggAgRgCIAUAAQAGAAAFgDQAEgEAAgGQAAgGgEgEQgFgEgGAAIgUAAg");
	this.shape_3.setTransform(44.725,14.175);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AgfAgQgMgNAAgTQAAgTAMgMQAMgNATAAQATAAANANQAMAMAAATQAAATgMANQgNANgTAAQgTAAgMgNgAgUgVQgIAIAAANQAAAOAIAIQAIAJAMAAQANAAAIgJQAIgIAAgOQAAgNgIgIQgIgJgNAAQgMAAgIAJg");
	this.shape_4.setTransform(33.175,14.175);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AAXArIAAgmIgsAAIAAAmIgQAAIAAhVIAQAAIAAAjIAsAAIAAgjIAPAAIAABVg");
	this.shape_5.setTransform(21.125,14.175);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AgiAfIAJgMQAMAMAOAAQAJAAAFgDQAEgEAAgFQAAgFgGgDQgEgCgJgCQgPgEgFgDQgLgGABgMQAAgLAIgHQAJgIANAAQAUAAANAMIgJAMQgKgKgPAAQgGAAgEADQgEADAAAFQAAAEAFADQAEACAJACQAPAEAGAEQAKAGAAAMQABAMgJAHQgIAIgRAAQgWAAgNgOg");
	this.shape_6.setTransform(10.15,14.175);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape},{t:this.line}]}).wait(1));

	// base
	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("rgba(255,255,255,0.008)").s().p("AnpBzIAAjlIPTAAIAADlg");
	this.shape_7.setTransform(50,12.5);

	this.timeline.addTween(cjs.Tween.get(this.shape_7).wait(1));

}).prototype = getMCSymbolPrototype(lib.m_productcta, new cjs.Rectangle(-24.5,1,150,23.4), null);


(lib.m_item = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		var root = this,
			cta = root.cta_mc;
			
		this.name_txt.font =  "15px ProximaNova-Semibold";
		this.price_txt.font = "13px ProximaNova-Semibold";
		
		this.name_txt.text.toUpperCase();
		
		cta.mouseChildren = false;
			
		cta.on("mouseover", function() {
			TweenMax.to(cta, .25, {scaleX:.85, scaleY:.85, ease:Back.easeOut});
			TweenMax.to(cta, .25, {scaleX:1.05, scaleY:1.05, ease:Back.easeOut});
		});
		
		cta.on("mouseout", function() {
			TweenMax.to(cta, .25, {scaleX:1, scaleY:1, ease:Back.easeOut});
			TweenMax.to(cta, .25, {scaleX:1, scaleY:1, ease:Back.easeOut});
		});
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// cta
	this.cta_mc = new lib.m_productcta();
	this.cta_mc.name = "cta_mc";
	this.cta_mc.parent = this;
	this.cta_mc.setTransform(150,446,1,1,0,0,0,50,12.5);

	this.timeline.addTween(cjs.Tween.get(this.cta_mc).wait(1));

	// hit
	this.hit_btn = new lib.m_itemhit();
	this.hit_btn.name = "hit_btn";
	this.hit_btn.parent = this;
	this.hit_btn.setTransform(0,0,1.0714,4.6875);
	new cjs.ButtonHelper(this.hit_btn, 0, 1, 2, false, new lib.m_itemhit(), 3);

	this.timeline.addTween(cjs.Tween.get(this.hit_btn).wait(1));

	// text
	this.price_txt = new cjs.Text("$100", "13px 'Proxima Nova Semibold'");
	this.price_txt.name = "price_txt";
	this.price_txt.textAlign = "center";
	this.price_txt.lineHeight = 18;
	this.price_txt.lineWidth = 296;
	this.price_txt.parent = this;
	this.price_txt.setTransform(150,397.5);

	this.name_txt = new cjs.Text("KARI METALLIC", "15px 'Proxima Nova Semibold'");
	this.name_txt.name = "name_txt";
	this.name_txt.textAlign = "center";
	this.name_txt.lineHeight = 14;
	this.name_txt.lineWidth = 296;
	this.name_txt.parent = this;
	this.name_txt.setTransform(150,378.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.name_txt},{t:this.price_txt}]}).wait(1));

	// image container
	this.image_mc = new lib.m_itemimage();
	this.image_mc.name = "image_mc";
	this.image_mc.parent = this;
	this.image_mc.setTransform(0,20);

	this.timeline.addTween(cjs.Tween.get(this.image_mc).wait(1));

}).prototype = getMCSymbolPrototype(lib.m_item, new cjs.Rectangle(0,0,300,600), null);


(lib.m_cta = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// text
	this.text_mc = new lib.m_ctatext();
	this.text_mc.name = "text_mc";
	this.text_mc.parent = this;
	this.text_mc.setTransform(100,19,1,1,0,0,0,100,10);

	this.timeline.addTween(cjs.Tween.get(this.text_mc).wait(1));

	// button
	this.base_mc = new lib.m_ctabutton();
	this.base_mc.name = "base_mc";
	this.base_mc.parent = this;
	this.base_mc.setTransform(100,20,1,1,0,0,0,100,20);

	this.timeline.addTween(cjs.Tween.get(this.base_mc).wait(1));

}).prototype = getMCSymbolPrototype(lib.m_cta, new cjs.Rectangle(0,0,200,40), null);


(lib.m_weather = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// lines
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(0,0,0,0.247)").s().dr(-0.5,-42.5,1,85);
	this.shape.setTransform(207.5,32.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(0,0,0,0.247)").s().dr(-0.5,-42.5,1,85);
	this.shape_1.setTransform(152.5,32.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("rgba(0,0,0,0.247)").s().dr(-0.5,-42.5,1,85);
	this.shape_2.setTransform(97.5,32.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("rgba(0,0,0,0.247)").s().dr(-0.5,-42.5,1,85);
	this.shape_3.setTransform(42.5,32.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	// days
	this.day4_mc = new lib.m_day();
	this.day4_mc.name = "day4_mc";
	this.day4_mc.parent = this;
	this.day4_mc.setTransform(235.05,32.5,1,1,0,0,0,15.2,32.5);

	this.day3_mc = new lib.m_day();
	this.day3_mc.name = "day3_mc";
	this.day3_mc.parent = this;
	this.day3_mc.setTransform(180,32.5,1,1,0,0,0,15,32.5);

	this.day2_mc = new lib.m_day();
	this.day2_mc.name = "day2_mc";
	this.day2_mc.parent = this;
	this.day2_mc.setTransform(125,32.5,1,1,0,0,0,15,32.5);

	this.day1_mc = new lib.m_day();
	this.day1_mc.name = "day1_mc";
	this.day1_mc.parent = this;
	this.day1_mc.setTransform(70,32.5,1,1,0,0,0,15,32.5);

	this.day0_mc = new lib.m_day();
	this.day0_mc.name = "day0_mc";
	this.day0_mc.parent = this;
	this.day0_mc.setTransform(15,32.5,1,1,0,0,0,15,32.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.day0_mc},{t:this.day1_mc},{t:this.day2_mc},{t:this.day3_mc},{t:this.day4_mc}]}).wait(1));

	// highlight
	this.highlight_mc = new lib.m_highlight();
	this.highlight_mc.name = "highlight_mc";
	this.highlight_mc.parent = this;
	this.highlight_mc.setTransform(208,32.5,1,1,0,0,0,0,37.5);

	this.timeline.addTween(cjs.Tween.get(this.highlight_mc).wait(1));

}).prototype = getMCSymbolPrototype(lib.m_weather, new cjs.Rectangle(-5,-10,263,85), null);


(lib.m_segments = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.segment4 = new lib.m_item();
	this.segment4.name = "segment4";
	this.segment4.parent = this;
	this.segment4.setTransform(1200,0);

	this.segment0dupe = new lib.m_item();
	this.segment0dupe.name = "segment0dupe";
	this.segment0dupe.parent = this;
	this.segment0dupe.setTransform(1500,0);

	this.segment4dupe = new lib.m_item();
	this.segment4dupe.name = "segment4dupe";
	this.segment4dupe.parent = this;
	this.segment4dupe.setTransform(-300,0);

	this.segment3 = new lib.m_item();
	this.segment3.name = "segment3";
	this.segment3.parent = this;
	this.segment3.setTransform(900,0);

	this.segment2 = new lib.m_item();
	this.segment2.name = "segment2";
	this.segment2.parent = this;
	this.segment2.setTransform(600,0);

	this.segment1 = new lib.m_item();
	this.segment1.name = "segment1";
	this.segment1.parent = this;
	this.segment1.setTransform(300,0);

	this.segment0 = new lib.m_item();
	this.segment0.name = "segment0";
	this.segment0.parent = this;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.segment0},{t:this.segment1},{t:this.segment2},{t:this.segment3},{t:this.segment4dupe},{t:this.segment0dupe},{t:this.segment4}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.m_segments, new cjs.Rectangle(-300,0,2100,457.9), null);


(lib.m_segmentcontainer = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// screen mcs
	this.segments_mc = new lib.m_segments();
	this.segments_mc.name = "segments_mc";
	this.segments_mc.parent = this;
	this.segments_mc.setTransform(-300,185,1,1,0,0,0,-300,185);

	this.timeline.addTween(cjs.Tween.get(this.segments_mc).wait(1));

}).prototype = getMCSymbolPrototype(lib.m_segmentcontainer, new cjs.Rectangle(-300,0,2100,457.9), null);


// stage content:
(lib.ugg_weatherAPI_women_300x600 = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		var root = this,
			screenPixelRatio = window.devicePixelRatio,
		    stageWidth = stage.canvas.width/screenPixelRatio,
		    stageHeight = stage.canvas.height/screenPixelRatio,
			bgScaleWidth = stageWidth/root.bg_mc.nominalBounds.width,
			bgScaleHeight = stageHeight/root.bg_mc.nominalBounds.height,
			hider = root.hider_mc,
			logo = root.logo_mc,
			cta = root.cta_mc,
			weather = root.weather_mc,
			headline = root.headline_mc,
			bg_texture = root.bg_texture,
			pics = root.images_mc,
			prev = root.prev_mc,
			next = root.next_mc,
			scroller = root.segmentContainer_mc,
			segments = root.segmentContainer_mc.segments_mc,
			segmentWidth = segments.segment0.nominalBounds.width,
			segmentCounter = 0,
			autoCounter = 0,
			numSegments = 5,
			delay = 5,
			time = .75,
			interacted = false,
			json,
			forecast,
			feed,
			ICON_BASE_URL = "https://s0.2mdn.net/creatives/assets/2382976/",
			BASE_URI = 'https://api.weatherunlocked.com/api/forecast/us.',
			APP_ID = '?app_id=a53261de',
			APP_KEY = '&app_key=6cf34bf89f35216416799a5fe34f5fb5',
			autoPlay = setInterval(handleAutoPlay, delay * 1000);
		
		function init() {
			root.bg_mc.scaleX = bgScaleWidth;
			root.bg_mc.scaleY = bgScaleHeight;
			
			console.log(userZip);
			makeRequest(buildURL(userZip), handleResponse);
		
			/*setTimeout(function(){
				startAnimation();
			}, 750);*/
			
			// init buttons
			
			var bgHit = root.bgHit;
			bgHit.on("click", doClickthrough);
			
			cta.mouseChildren = false;
			
			cta.on("mouseover", function() {
				TweenMax.to(cta.base_mc, .25, {scaleX:.85, scaleY:.85, ease:Back.easeOut});
				TweenMax.to(cta.text_mc, .25, {scaleX:1.05, scaleY:1.05, ease:Back.easeOut});
			});
			
			cta.on("mouseout", function() {
				TweenMax.to(cta.base_mc, .25, {scaleX:1, scaleY:1, ease:Back.easeOut});
				TweenMax.to(cta.text_mc, .25, {scaleX:1, scaleY:1, ease:Back.easeOut});
			});
			
			prev.on("click", prevClick);
			next.on("click", nextClick);
			cta.on("click", doClickthrough);
			
			headline.shadow = new createjs.Shadow("rgba(0,0,0,1)",0,0,40);
		}
		
		
		function startAnimation() {
			
			TweenMax.to(hider, .25, {alpha:0, onComplete:function() {
				hider.visible = false;
			}});
			
			// frame 1
			TweenMax.set(scroller, {alpha:0});
			TweenMax.from(headline, .5, {delay:.5, alpha:0, ease:Back.easeOut});
			TweenMax.from(pics, 1, {delay:.25, alpha:0, ease:Power2.easeOut});
			
			// frame 2
			TweenMax.from(logo, .5, {delay:delay, alpha:0, ease:Back.easeOut});	
			TweenMax.to(headline, .5, {delay:delay, alpha:0, ease:Back.easeOut});
			TweenMax.to(bg_texture, 1, {delay:delay, alpha:1, ease:Back.easeOut});
			TweenMax.to(pics, .5, {delay:delay, alpha:0});
			TweenMax.to(weather, 1, {delay:delay, y:170, alpha:1, ease:Back.easeOut});
			TweenMax.to(scroller, .5, {delay:delay, alpha:1, ease:Power2.easeOut});
			
			TweenMax.from(cta, 1, {delay:delay, scaleX:0, scaleY:0, ease:Back.easeOut});
			TweenMax.from(prev, 1, {delay:delay, x:-20, ease:Back.easeOut});
			TweenMax.from(next, 1, {delay:delay, x:300, ease:Back.easeOut});
		}
		
		function getUrlParameter(name) {
		    name = name.replace(/[\[]/, '\\[').replace(/[\]]/, '\\]');
		    var regex = new RegExp('[\\?&]' + name + '=([^&#]*)');
		    var results = regex.exec(parent.document.location.search);
		    return results === null ? '' : decodeURIComponent(results[1].replace(/\+/g, ' '));
		};
		
		init();
		
		
		////// autoplay code ////// 
		
		function handleAutoPlay() {
			autoCounter++;
			segmentCounter++;
			if (autoCounter > numSegments-1) {
				autoCounter = 0;
				segmentCounter = 0;
				TweenMax.set(segments, {x:0});
			}
			
			swap(autoCounter);
		}
		
		function killAutoPlay() {
			interacted = true;
			if (autoPlay != null) {
				clearInterval(autoPlay);
				autoPlay = null;
			}
		}
		
		setTimeout(function(){ 
			if(!interacted){
				clearInterval(autoPlay);
			}
		}, 30000);
		
		
		////// weather code //////
		
		function buildURL(zip) {
			var url = BASE_URI + zip + APP_ID + APP_KEY;
			return url;
		}
		
		function makeRequest(url, callback)
		{
			var xmlHttp = new XMLHttpRequest();
			
			xmlHttp.onreadystatechange = function(e) {
			
				if (xmlHttp.readyState == 4 && xmlHttp.status == 200) {
					callback(xmlHttp.responseText);
				}
			}
			
			xmlHttp.open("GET", url, true);
			xmlHttp.send();
		}
		
		function handleResponse(response) { 
			json = JSON.parse(response); 
			forecast = json.Days;
			
			//console.log(forecast);
		
			for (var i = 0; i < 5; i++) {
				var timeframe
					w = i + 1;
				
				// if full timeframe, grab mid-day, else grab first
				if (forecast[i].Timeframes.length == 8) {
					timeframe = forecast[w].Timeframes[3];// mid-day
				} else {
					timeframe = forecast[w].Timeframes[0]; // first
				}
				
				
				var date = timeframe.date,
					temp = Math.round(timeframe.temp_f),
					icon = timeframe.wx_icon,
					code = timeframe.wx_code,
					day = moment(date,'DD-MM-YYYY'),
					day_mc = weather["day" + i + "_mc"];
				//console.log(date);
			
				day_mc.day_txt.text = day.format('ddd').toUpperCase();
				day_mc.temp_txt.text = temp + "°";
				
				loadIcon(icon, day_mc.icon_mc);
			}
			
			// DETECT IF MANUALLY SET FOR TEST IN URL
			// 10 = rain, 70 = snow, 1 = cold
			var testCode = getUrlVars()["testCode"];
			if (testCode) {
				switchContent(testCode);
			}
			else {
				switchContent(timeframe.wx_code);
			}
		}
		
		function loadIcon(icon, mc) {
			var img = new Image();
			
			img.onload = function() {
				var bitmap = new createjs.Bitmap(img);
				//bitmap.x = 0;
				mc.addChild(bitmap);
			};
			
			img.crossOrigin = "Anonymous";
			img.src = ICON_BASE_URL + icon;
		}
		
		function getUrlVars() {
		    var vars = {};
		    var parts = window.location.href.replace(/[?&]+([^=&]+)=([^&]*)/gi, function(m,key,value) {
		        vars[key] = value;
		    });
		    return vars;
		}
		
		function switchContent(code) {
			// check for rain codes
			if (code == 10 || code == 21 || code == 23 || code == 24 || code == 29 || code == 50 || code == 51 || code == 56 || code == 57 || code == 60 || code == 61 || code == 62 || code == 63 || code == 64 || code == 65 || code == 66 || code == 67 || code == 68 || code == 69 || code == 80 || code == 81 || code == 82 || code == 83 || code == 84 || code == 91 || code == 92) {
				pics.gotoAndStop(0);
				headline.gotoAndStop(0);
				bg_texture.gotoAndStop(0);
				//initFeed(rainy);
				initFeed(rain2019);
			}
			// check for snowy codes
			else if (code == 38 || code == 39 || code == 70 || code == 71 || code == 72 || code == 73 || code == 74 || code == 75 || code == 79 || code == 85 || code == 86 || code == 87 || code == 88 || code == 93 || code == 94) {
				pics.gotoAndStop(1);
				headline.gotoAndStop(1);
				bg_texture.gotoAndStop(1);
				//initFeed(snowy);
				initFeed(snow2019);
			}
			else{
				pics.gotoAndStop(2);
				headline.gotoAndStop(2);
				bg_texture.gotoAndStop(2);
				//initFeed(cold);
				initFeed(cold2019);
			}
			startAnimation();
		}
		
		
		////// scroller code ////// 
		
		function prevClick(e) {
			killAutoPlay();
			prev.mouseEnabled = false;
			segmentCounter--;
			
			if(segmentCounter >= 0){
				TweenMax.to(segments, time, {x:"+=" + segmentWidth, ease:Power2.easeOut});
			}
			
			if(segmentCounter < 0){
				TweenMax.to(segments, time, {x:"+=" + segmentWidth, ease:Power2.easeOut, onComplete:resetPrev});
			}
			
			setTimeout(function(){ prev.mouseEnabled = true; }, 750);
		}
		
		function nextClick(){	
			killAutoPlay();
			next.mouseEnabled = false;
			segmentCounter++;
			
			if(segmentCounter <= numSegments-1){ 
				TweenMax.to(segments, time, {x:"-=" + segmentWidth, ease:Power2.easeOut});
			}
			
			if(segmentCounter > numSegments-1){
				TweenMax.to(segments, time, {x:"-=" + segmentWidth, ease:Power2.easeOut, onComplete:resetNext});
			}
			
			setTimeout(function(){ next.mouseEnabled = true; }, 750);
		}
		
		function resetPrev(){
			segments.x = -numSegments * segmentWidth;
			segmentCounter = numSegments-1;
		}
		
		function resetNext(){
			segments.x = -segmentWidth;
			segmentCounter = 0;
		}
		
		function swap(index) {
			TweenMax.to(segments, time, {x: -segmentWidth * (index + 1), ease:Power2.easeOut});
		}
		
		
		////// feed/item code ////// 
		
		var queue = new createjs.LoadQueue(),
			items = [
				segments.segment0,
				segments.segment1,
				segments.segment2,
				segments.segment3,
				segments.segment4
			],
			dupe_first = segments.segment0dupe,
			dupe_last = segments.segment4dupe;
			
		function onLoadComplete(e) {
			
			var images = queue.getItems(true);
			console.log(images.length);
		
			for (var i=0; i < images.length; i++) {
				
				var item = items[i];
				
				populateItem(item, images[i].result, feed[i]);
				
				// populate duplicate segments
				switch(i) {
					case 0:
						populateItem(dupe_first, images[i].result, feed[i]);
						break;
					case 4:
						populateItem(dupe_last, images[i].result, feed[i]);
						break;
				}
			}
		}
		
		function populateItem(item, image, feed) {
			var bitmap = new createjs.Bitmap(image);
			bitmap.x = 60;
			bitmap.y = 160;
			item.image_mc.addChild(bitmap);
			item.name_txt.text = feed.name.toUpperCase();
			item.price_txt.text = feed.price;
			item.url = feed.url;
			item.hit_btn.on('click', doDynamicClickthrough);
			item.cta_mc.on('click', doDynamicClickthrough);
		}
		
		
		function initFeed(data) {
			feed = data;
			queue.on('complete', onLoadComplete);
			queue.loadManifest(feed);		
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// hider
	this.hider_mc = new lib.m_hider();
	this.hider_mc.name = "hider_mc";
	this.hider_mc.parent = this;
	this.hider_mc.setTransform(150,300,1,1,0,0,0,150,300);

	this.timeline.addTween(cjs.Tween.get(this.hider_mc).wait(1));

	// logo
	this.logo_mc = new lib.m_logo();
	this.logo_mc.name = "logo_mc";
	this.logo_mc.parent = this;
	this.logo_mc.setTransform(149.5,48.5,0.2089,0.2088,0,0,0,299.2,136.4);

	this.timeline.addTween(cjs.Tween.get(this.logo_mc).wait(1));

	// headline
	this.headline_mc = new lib.headline_mc();
	this.headline_mc.name = "headline_mc";
	this.headline_mc.parent = this;
	this.headline_mc.setTransform(0.05,234.85);

	this.timeline.addTween(cjs.Tween.get(this.headline_mc).wait(1));

	// weather
	this.weather_mc = new lib.m_weather();
	this.weather_mc.name = "weather_mc";
	this.weather_mc.parent = this;
	this.weather_mc.setTransform(150,242.5,1,1,0,0,0,125,32.5);
	this.weather_mc.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.weather_mc).wait(1));

	// nav arrows
	this.prev_mc = new lib.m_arrowbutton();
	this.prev_mc.name = "prev_mc";
	this.prev_mc.parent = this;
	this.prev_mc.setTransform(19,271,0.5,0.5,90,0,0,2,42);

	this.next_mc = new lib.m_arrowbutton();
	this.next_mc.name = "next_mc";
	this.next_mc.parent = this;
	this.next_mc.setTransform(260,270,0.5,0.5,-90,0,0,180,0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.next_mc},{t:this.prev_mc}]}).wait(1));

	// cta
	this.cta_mc = new lib.m_cta();
	this.cta_mc.name = "cta_mc";
	this.cta_mc.parent = this;
	this.cta_mc.setTransform(150,560,1,1,0,0,0,100,20);

	this.timeline.addTween(cjs.Tween.get(this.cta_mc).wait(1));

	// scroller
	this.segmentContainer_mc = new lib.m_segmentcontainer();
	this.segmentContainer_mc.name = "segmentContainer_mc";
	this.segmentContainer_mc.parent = this;
	this.segmentContainer_mc.setTransform(-300,0,1,1,0,0,0,-300,0);

	this.timeline.addTween(cjs.Tween.get(this.segmentContainer_mc).wait(1));

	// bgHit
	this.bgHit = new lib.m_itemhit();
	this.bgHit.name = "bgHit";
	this.bgHit.parent = this;
	this.bgHit.setTransform(0,0,1.0714,4.6875);
	new cjs.ButtonHelper(this.bgHit, 0, 1, 2, false, new lib.m_itemhit(), 3);

	this.timeline.addTween(cjs.Tween.get(this.bgHit).wait(1));

	// images
	this.images_mc = new lib.m_images();
	this.images_mc.name = "images_mc";
	this.images_mc.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.images_mc).wait(1));

	// bg texture
	this.bg_texture = new lib.bg_texture();
	this.bg_texture.name = "bg_texture";
	this.bg_texture.parent = this;
	this.bg_texture.setTransform(149,299,1,1,0,0,0,149,299);
	this.bg_texture.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.bg_texture).wait(1));

	// bg_cover
	this.bg_mc = new lib.bg_mc();
	this.bg_mc.name = "bg_mc";
	this.bg_mc.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.bg_mc).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150,300,1950,300);
// library properties:
lib.properties = {
	id: '26821785911F4BD59B7112D85822C144',
	width: 300,
	height: 600,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"ugg_weatherAPI_women_300x600_atlas_NP_.jpg?1574275494038", id:"ugg_weatherAPI_women_300x600_atlas_NP_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['26821785911F4BD59B7112D85822C144'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}			
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;			
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});			
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;			
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;